services:
  - type: web
    name: ofi-reporting
    env: static
    buildCommand: npm run build
    staticPublishPath: dist/ofi-reporting/browser
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
